### ISSUE TITLE
Invariant generation

### ISSUE THREAD

**Issue by pierreganty** [pierreganty/mist#17]
for the TTS to SPEC translation it is useful for the backward search to have an invariant.
(algorithm other than backward do not use invariants)

The invariant is
`s0=1`, ...,`sN=1` where `N` is the index used by the translation. What is nice is that
the invariant is the same for all translations (unary, binary, Nary). Intuitively it reads as follows:
the sum `1*s0 + ... + 1*sN` stays the same after firing a transition.
Initially (that is by the initial marking) this sum is equal to `1` (in the unary case), `log N` (in the binary case) and `N` (in the Nary case).

**Comment by pierreganty** [comment]
@pevalme a small description of the meaning of the `invariants` section

**Comment by pierreganty** [comment]
@pevalme what is the current status of this issue?

**Comment by pevalme** [comment]
I have check some examples and the number of iterations are just the same when using the three different translations. The number of arcs or elems sometimes is not the same but I think this was not a problem, am I right?

**Comment by pierreganty** [comment]
@pevalme Is this a solved issue?

**Comment by pierreganty** [comment]
it is solved
