### ISSUE TITLE
directory renaming

### ISSUE THREAD

**Issue by pierreganty** [pierreganty/mist#18]
Between `examples`, `tests` and `regressions` it is not clear what the difference is.
Why not renaming `tests` into `scripts` and also renaming `test_examples.py` into `run_benchmarks.py`? In any case, we should add in all these 3 directories a `README.md` file explaining the purpose of it.
For  `regressions` and `examples` perhaps renaming them to `regression-tests` and `benchmarks` would make more sense. Any ideas?

**Comment by pierreganty** [comment]
@pevalme did you see this?

**Comment by pevalme** [comment]
I have just seen this issues today and I'm already working on it

**Comment by pevalme** [comment]
Right now there is no folder called regressions, should I add it?
Do we really need a README for the scripts folder?

I think that with the changes test_examples -> run_benchmarks and tests->scripts it's clear. You provide some examples and also an script to check that the tool works fine with these examples.
I'm going to add the expected results for the examples without it.

I'm not use to the "real world" so my opinion is based on how I work with other students. If you think we should add a regressions folder with small examples I could do it (which is more, I already have some small examples that I have been using to check some parts of my changes but I should complete them carefully to cover all possibilities if we want to add a good regressions folder)

**Comment by pierreganty** [comment]
There is a folder called [`regression`](https://github.com/pierreganty/mist/tree/master/regression).
I think it makes sense to rename so as to have `scripts`, `regression-tests` and `benchmarks`.
It makes sense to have both `benchmarks` and `regression-tests`. `benchmarks` are problem instances used to compare tool performance. Those problem instances are drawn from existing programs or protocols. `regression-tests` are just sanity checks to make sure the tool behaves as expected.
The problem instances in `regression-tests` should **not** be used to compare between tools (and a `README.md` file in `regression-tests` stating this fact would be useful).

Besides renaming, make sure the root README.md and the wiki are reflecting this change if needed.

What do you mean when you write?
> I'm going to add the expected results for the examples without it.

**Comment by pevalme** [comment]
I forgot that I had added this folder and as I created the branch before adding this changes to the master I couldn't see the folder. 

I'm working on it right now.

**Comment by pierreganty** [comment]
Is there a PR coming to merge `regression` into `regression-tests` ?

**Comment by pevalme** [comment]
I'm preparing a PR with several changes with this one among them.

**Comment by pierreganty** [comment]
commit 57f912b001fe54428a73e6223d54d6686433802b brings the final touch
