### ISSUE TITLE
Update warning note in the wiki

### ISSUE THREAD

**Issue by pierreganty** [pierreganty/mist#19]
The [wiki](https://github.com/pierreganty/mist/wiki) contains a warning note which might not be valid anymore.

**Comment by pierreganty** [comment]
@pevalme the tool now tells you when the input file is not a Petri net so the warning note can be removed.

**Comment by pevalme** [comment]
Wardin removed. We still have to add the eec-cegar description to the wiki. 
Should I close this issue anyway?

**Comment by pierreganty** [comment]
yes
