### ISSUE TITLE
Layout of Graphs

### ISSUE THREAD

**Issue by pierreganty** [pierreganty/mist#24]
@pevalme Currently graphs in the web browser are one column.
It would be great to better use the screen real estate with the graphs displayed in table (tile layout).
What are the possible options ?

**Comment by pierreganty** [comment]
@ pevalme Also it would be super cool to be able to hide a graph. For example, right now I am looking at 20 something graphs but I want to discard some and only stare at 9.

**Comment by pevalme** [comment]
All this implies just a change on the .html file.

I think that, with the current .html file, it will be very easy to add a button to display or not each graph.

About the way the graphs are displayed, I'm not sure but I think it's also easy but maybe it can cause some problems when displaying or not some graphs. If you show graphs two by two and disable one, should be an space or the graphs must reorganize theirself?. 

I'll work on it.

**Comment by pierreganty** [comment]
solved by #25
