### ISSUE TITLE
Improve documentation of the typechecking

### ISSUE THREAD

**Issue by pierreganty** [pierreganty/mist#32]
@pevalme can you revise the documentation of [typechecking.c](https://github.com/pierreganty/mist/blob/master/src/typechecking.c) ? The current documentation does not explain what triggers `return false`.
Also the use of `MAX_INT` looks suspicious (why 16bits?).

**Comment by pevalme** [comment]
I'll try to add some explanations to the code.

I don't know why I decided to use this value as a MAX_INT. I'll fix it

**Comment by pierreganty** [comment]
Solved by #33
